In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data=pd.read_csv('/content/purchase_history.csv')

In [ ]:
data

Customer ID  Gender  Age  Salary Product ID  Price  Purchased
0              1  Female   49   61000        P01   2000          1
1              2    Male   36   30000        P02   2000          1
2              3  Female   26   81000        P02   3500          1
3              4  Female   32   74000        P01   7000          0
4              5  Female   42   56000        P01   5000          0
..           ...     ...  ...     ...        ...    ...        ...
995          996    Male   21   73000        P02   5000          1
996          997    Male   62   54000        P01   5000          0
997          998  Female   41   20000        P03   2000          0
998          999    Male   22   29000        P03   5000          0
999         1000  Female   49   36000        P03   3500          0

[1000 rows x 7 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Customer ID  1000 non-null   int64 
 1   Gender       1000 non-null   object
 2   Age          1000 non-null   int64 
 3   Salary       1000 non-null   int64 
 4   Product ID   1000 non-null   object
 5   Price        1000 non-null   int64 
 6   Purchased    1000 non-null   int64 
dtypes: int64(5), object(2)
memory usage: 54.8+ KB


In [ ]:
gender_encoded= pd.get_dummies(data['Gender'], drop_first= True)

In [ ]:
gender_encoded

Male
0       0
1       1
2       0
3       0
4       0
..    ...
995     1
996     1
997     0
998     1
999     0

[1000 rows x 1 columns]

In [ ]:
data=pd.concat([data,gender_encoded],axis=1)

In [ ]:
X=data[['Male', 'Age','Salary','Price']].to_numpy()

In [ ]:
X

array([[    0,    49, 61000,  2000],
       [    1,    36, 30000,  2000],
       [    0,    26, 81000,  3500],
       ...,
       [    0,    41, 20000,  2000],
       [    1,    22, 29000,  5000],
       [    0,    49, 36000,  3500]])

In [ ]:
y=data['Purchased'].to_numpy()

In [ ]:
y

array([1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,

In [ ]:
!pip install scikit-learn

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
X_train

array([[    1,    26, 28000,  5000],
       [    1,    54, 21000,  7000],
       [    0,    42, 22000,  5000],
       ...,
       [    0,    59, 91000,  2000],
       [    0,    31, 82000,  2000],
       [    0,    20, 34000,  5000]])

In [ ]:
X_test

array([[     1,     54,  36000,   5000],
       [     0,     54,  60000,   7000],
       [     1,     25,  39000,   2000],
       [     0,     39,  38000,   7000],
       [     1,     28,  37000,   5000],
       [     1,     52,  42000,   2000],
       [     0,     43,  25000,   7000],
       [     0,     40,  22000,   5000],
       [     0,     18,  23000,   3500],
       [     1,     62,  40000,   5000],
       [     1,     53,  66000,   5000],
       [     0,     50,  38000,   7000],
       [     0,     49,  59000,   7000],
       [     0,     56,  97000,   2000],
       [     1,     41,  44000,   3500],
       [     1,     37,  74000,   2000],
       [     0,     51,  23000,   5000],
       [     1,     54,  29000,   2000],
       [     1,     30,  48000,   3500],
       [     1,     56,  87000,   3500],
       [     0,     61,  75000,   7000],
       [     1,     52,  49000,   7000],
       [     0,     38, 100000,   2000],
       [     0,     40,  79000,   5000],
       [     1, 

In [ ]:
y_train

array([0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,

In [ ]:
y_test

array([0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0])

In [ ]:
len(X_train)

800

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler=StandardScaler()

X_train=scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)

In [ ]:
X_train

array([[ 1.08347268, -1.09076887, -1.30749141,  0.30934614],
       [ 1.08347268,  0.97668947, -1.60377078,  1.39955279],
       [-0.92295821,  0.0906359 , -1.56144515,  0.30934614],
       ...,
       [-0.92295821,  1.34587846,  1.35902286, -1.32596384],
       [-0.92295821, -0.72157988,  0.97809225, -1.32596384],
       [-0.92295821, -1.53379565, -1.05353767,  0.30934614]])

In [ ]:
X_test

array([[ 0.91370804,  0.84165121, -0.92674628,  0.29135523],
       [-1.0944415 ,  0.84165121,  0.09493083,  1.3460348 ],
       [ 0.91370804, -1.16805526, -0.79903664, -1.29066412],
       [-1.0944415 , -0.19785214, -0.84160652,  1.3460348 ],
       [ 0.91370804, -0.96015459, -0.8841764 ,  0.29135523],
       [ 0.91370804,  0.70305076, -0.671327  , -1.29066412],
       [-1.0944415 ,  0.07934876, -1.39501496,  1.3460348 ],
       [-1.0944415 , -0.12855191, -1.5227246 ,  0.29135523],
       [-1.0944415 , -1.65315683, -1.48015472, -0.49965444],
       [ 0.91370804,  1.396053  , -0.75646676,  0.29135523],
       [ 0.91370804,  0.77235099,  0.35035011,  0.29135523],
       [-1.0944415 ,  0.56445032, -0.84160652,  1.3460348 ],
       [-1.0944415 ,  0.49515009,  0.05236095,  1.3460348 ],
       [-1.0944415 ,  0.98025166,  1.67001638, -1.29066412],
       [ 0.91370804, -0.05925169, -0.58618724, -0.49965444],
       [ 0.91370804, -0.33645258,  0.69090915, -1.29066412],
       [-1.0944415 ,  0.

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
k=5
knn=KNeighborsClassifier(n_neighbors=k)

In [ ]:
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [ ]:
y_pred=knn.predict(X_test)

In [ ]:
y_pred

array([1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0])

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy=accuracy_score(y_test,y_pred)

In [ ]:
accuracy

0.765

In [ ]:
import pickle

In [ ]:
with open('knn_model.pickle','wb') as f:
  pickle.dump(knn,f)

In [ ]:
with open('scaler.pickle','wb') as f:
  pickle.dump(scaler,f)